##########
# collectionbuilder-sa
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-sa
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url:
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /Information/Collections/Furer
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-sa

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Lloyd C. Furer Cross Sections
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "After 20 years in the oil industry, Lloyd Furer joined Indiana University and, among other research activities, taught surface geology for 10 years at the Indiana field station near Cardwell, Montana. Since retiring, Lloyd has spent decades correlating subsurface formations in the western U.S. based on his knowledge of surface geology and thousands of geophysical logs from Montana, Wyoming, Colorado, and the Dakotas. This collection of over 50 cross sections represents a portion of Lloyd Furer’s correlation work in Montana."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: montana;furer;cross sections;
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Montana Bureau of Mines and Geology
# Organization branding
organization-name: "Montana Bureau of Mines and Geology"
organization-link: https://www.mbmg.mtech.edu/main.asp
organization-logo-banner: assets\img\MBMG2012LogoTransparent.png
organization-logo-nav: assets\img\logombmg.png

##########
# COLLECTION SETTINGS
#
# provide location of the digital objects folder,
# If using local folder, dir name with proceeding slash. If using external web location, provide full URL
objects: /objects 
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: furer-metadata
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'furer-metadata'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
